### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by J-Kappes** [ulville/eepresetselector#12]
would be nice to have.

**Comment by ulville** [comment]
I thought about adding keyboard shortcuts before but discovered that one can already focus on the top bar by <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Tab</kbd> and navigate using the <kbd>Arrow Keys</kbd>, it's not a straightforward solution though.  And because I haven't felt any major need for keyboard shortcuts I haven't implemented it yet. I was basically waiting for a request to work on it.

Could you give me more details about your proposal? Keyboard shortcuts for which actions? Is it only for opening/closing the menu? Or is it something more specific?

**Comment by J-Kappes** [comment]
> one can already focus on the top bar by Ctrl + Alt + Tab and navigate using the Arrow Keys

Oh, thanks for the workaround.

> Keyboard shortcuts for which actions?

I was thinking shortcuts to cycle through the presets, forwards and backwards, while wrapping around. I only have two presets, so forward would be enough for me personally.

**Comment by ulville** [comment]
I have finally found time to work on this and committed the first usable implementation. There are no preferences window yet so shortcuts are unchangeable by the user.

Default shortcuts are: 

- <kbd>Ctrl</kbd>+<kbd>Super</kbd>+<kbd>o</kbd> for cycling through output presets and
- <kbd>Ctrl</kbd>+<kbd>Super</kbd>+<kbd>i</kbd> for cycling through input presets

I'll implement the Prefs window and release a new version ASAP. Hopefully it won't take long. :crossed_fingers:  

By the time you can clone the repo and install it using the [install script](https://github.com/ulville/eepresetselector#install-script)

**Comment by J-Kappes** [comment]
> By the time you can clone the repo and install it using the [install script](https://github.com/ulville/eepresetselector#install-script)

Thanks. Just tried it. 👌

**Comment by ulville** [comment]
[Release version 16](https://github.com/ulville/eepresetselector/releases/tag/v16) closes this
