### ISSUE TITLE
Check out these icons

### ISSUE THREAD

**Issue by sfknhagvkas** [ulville/eepresetselector#13]
Maybe you could use these original icons. I think they are more in keeping with the GNOME style.

SVG icon:

![easy-effects-symbolic](https://github.com/ulville/eepresetselector/assets/107754716/e1d52f88-270e-41c3-8682-1f88858a1cb4)

PNG 16x16 icon:

![easy-effects-symbolic](https://github.com/ulville/eepresetselector/assets/107754716/a40de849-ccba-4ce2-b630-38cfaa259cb0)

**Comment by ulville** [comment]
Hi thanks for your feedback.

Where are these icons from? I initially thought it's [this symbolic icon ![](https://raw.githubusercontent.com/wwmm/easyeffects/master/data/com.github.wwmm.easyeffects-symbolic.svg)](https://github.com/wwmm/easyeffects/blob/master/data/com.github.wwmm.easyeffects-symbolic.svg) from Easy Effects project but now I checked and it's different. It's more useful when you provide the sources of the assets you're suggesting.

Anyways I haven't used the icon from Easy Effects project because;

1. Respect for the designer, but I'm not a fan of it
2. This is a complementary but different project so I didn't want to make people assume it's an official part of the Easy Effects 
3. Also I wanted this extension to have it's unique identity while being related to the Easy Effects

So I designed [this ![](https://raw.githubusercontent.com/ulville/eepresetselector/master/eepresetselector%40ulville.github.io/icons/eepresetselector-symbolic.svg)](https://github.com/ulville/eepresetselector/blob/master/eepresetselector%40ulville.github.io/icons/eepresetselector-symbolic.svg) similar but different icon which is now in use. And I don't think the icon you've suggested gives enough resemblance to the Easy Effects branding. It's more like a generic settings panel kind of icon.

Also I'm curious, what makes you think that my icon isn't in line with the GNOME style?

**Comment by sfknhagvkas** [comment]
@ulville Well I clearly stated that this is original icon. It means it was made by myself.

Icon from Easy Effects is pretty cool too. I haven't seen it. Too be fair, I don't understand your reasoning behind not using it. Seems a little odd to me that you don't want to associate with Easy Effects while making extension for them.

Your design would be okay if it weren't for this semi-transparent circle in the background. It's terrible, completely ruins the icon and makes it look like a blurry blob. If you look through the GNOME symbolic icons you would see that none of them use semi-transparent elements that intersect with other elements. And for a good reason.

Anyway, thanks for your work.

**Comment by ulville** [comment]
@sfknhagvkas  I've pushed a new branch [simpler-icon](https://github.com/ulville/eepresetselector/tree/simpler-icon). Basically removed the semi-transparent circle in the background.

8eddece is the relevant commit and [here](https://github.com/ulville/eepresetselector/blob/simpler-icon/eepresetselector%40ulville.github.io/icons/eepresetselector-symbolic.svg) is the icon itself. Take a look at it.

Here is a side by side comparison of the two icons
![Ekran Görüntüsü - 2023-06-12 23-00-33](https://github.com/ulville/eepresetselector/assets/50755946/9bb52172-f3e8-4e4e-bc6f-0002a6360400)

I don't think the current one is that bad and I don't see it as a blurry blob either. Rather the circle gives it more of a depth and integrity in my opinion. Without the circle it feels a bit skinny and disintegrated. But I would agree that it's more contrasty and legible.

I still haven't made my mind about which one I'm going to use but I'll consider other opinions as well. 

---

> Icon from Easy Effects is pretty cool too.

From a distance it looks like a pair of slippers instead of three vertical sliders

> Seems a little odd to me that you don't want to associate with Easy Effects while making extension for them.

It's not like I don't want to associate with them, rather like I don't want users to think this extension to be an official part of them. So they don't go to them for help about the issues they might encounter while using this extension. Also even though it's all FOSS and everything It didn't felt right to take their artwork because it's their own brand. And as I said before. I'm not a fan of their symbolic icon either

**Comment by sfknhagvkas** [comment]
> Here is a side by side comparison of the two icons

Yeah, it's much better without background.

> I don't think the current one is that bad and I don't see it as a blurry blob either.

Maybe it depends on the resolution of the screen. 16px version definitely is blurry for me. 

> Rather the circle gives it more of a depth and integrity in my opinion.

It's alright for big icon, but pretty bad for small symbolic one.
