### ISSUE TITLE
Missing GNOME 42 compatibility

### ISSUE THREAD

**Issue by iadegesso** [ulville/eepresetselector#3]
Since GNOME 42 has been released, this extension is not supported anymore...

Iade

**Comment by ulville** [comment]
Hi, thanks for the issue. Even though I don't expect any problems, because of the lack of free time I haven't yet to be able to test it on GNOME 42. So I didn't update the metadata yet. I will test it myself as soon as possible but by the time you can download the extension manually and edit the metadata.json file to add "42" to "shell-version" and install it that way. If it works as expected you can use it until I update the version. 

Please let me know if you encounter any errors or unexpected behaviors or if it works as expected on G42. According to your feedback (if it works with no problems on GNOME 42) I can update the version sooner.

**Comment by ulville** [comment]
I tested it on Fedora 36 beta and it works as expected so https://github.com/ulville/eepresetselector/commit/0c659cc93ce9a71375d915e96e3558185384b62d adds GNOME 42 support and it's on version 4 now. Uploaded it to extensions.gnome.org
